Squashed commit of the following:
commit 3ec7ee8b2e5969c82235c461a7b075bb29938419
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 18:05:12 2025 +0200

    [selenium_customized]

commit ca6afe97eca72d9d6de06c39395a7f766ebb1da8
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 17:20:28 2025 +0200

    [selenium_customized]

commit 082cf477846ec2c10cd50bc549635bdfe42ea27d
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 14:42:45 2025 +0200

    alias odoo vscode

commit e1b8a551a4f9d3c90e2356aed974bf3f7c55adb0
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 14:19:49 2025 +0200

    [selenium_customized]

commit d6ab5cc21491c6a0c5f5f5ad83fb22006109c13c
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 14:12:45 2025 +0200

    users

commit fe77b8dc558e5ce89bc30c38f2b0b16df3c87768
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 14:03:16 2025 +0200

    automated highest python version

commit 40f92652e36128c8cdc2e7860853f76835d91921
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 13:42:17 2025 +0200

    showing settings

commit 1b6ba3f74b67ebc9c9d63b432fb016c21560279e
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 12:12:53 2025 +0200

    fix

commit a7f64d6ffa8a536f63bece6a101c8a9ef7be0175
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 12:11:29 2025 +0200

    fixes

commit 0890add27f4074e0640501a49a0dc2969893274d
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 11:50:17 2025 +0200

    removed libpostal, docker client in odoo

commit 72b56b91c37bd5f7a0a76e6fade0959ea83af686
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 11:43:45 2025 +0200

    docker gid moved

commit f1a9990e1037dfc4937b3e4a446f25ce9a4f4e0c
Author: Marc Wimmer <marc@zebroo.de>
Date:   Mon Aug 4 00:05:56 2025 +0200

    docker gid

commit f74321534856b18f6a826e49004b0aad3ee26c72
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sun Aug 3 23:31:21 2025 +0200

    removed pip args apt args

commit ee5a152a869a2621a1e9d985f478d63946b9c10b
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sun Aug 3 18:52:45 2025 +0200

    [selenium_customized]

commit 283fa71df72dbe439110ea40a6e75016253170d1
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sun Aug 3 17:22:28 2025 +0200

    .

commit 1e75afd69f0c9e14c5b68f623b73cc5c22275765
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sun Aug 3 16:31:22 2025 +0200

    cacher

commit 3968fb872df5d8ffc13aba2af9d6c0fd67f98f7c
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sat Aug 2 17:26:06 2025 +0200

    [selenium_customized]

commit ec3384a4c3db3ad6018c4c0656746780f7814f38
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sat Aug 2 17:25:41 2025 +0200

    [selenium_customized]

commit 0bdb7df32f5d6b455d7768fcc64166059b7e4a11
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sat Aug 2 16:53:51 2025 +0200

    [selenium_customized]

commit 3fdf9266f5840742f464052e429d327fea39e0cd
Author: Marc Wimmer <marc@zebroo.de>
Date:   Sat Aug 2 16:53:47 2025 +0200

    [selenium_customized]

commit bd0cc77a2ec5f3572f574b79e5915737398bb5d1
Author: Marc Wimmer <marc@zebroo.de>
Date:   Fri Aug 1 23:04:03 2025 +0200

    [selenium_customized]

commit f102333439583358f67d55bbbcebca6335fd2eb9
Author: Marc Wimmer <marc@itewimmer.de>
Date:   Thu Jul 31 13:59:14 2025 +0200

    Update README.md

    completion

    odoo upgrade

    black

    [main]

    [main]

    [main]

    [main]

    main: Fixed

    reinstall

    cups

    ports

    Update install.sh

    removed pypi

    fix lang import and settings

    [selenium_customized]

    [selenium_customized]

    [selenium_customized]

    [selenium_customized]

    maximaed

diff --git a/common_snippets/wodoo b/common_snippets/wodoo
--- a/common_snippets/wodoo
+++ b/common_snippets/wodoo
@@ -1,20 +1,20 @@
+# Check if build-time user is root
+RUN if [ "$(id -u)" -ne 0 ]; then \
+      echo "ERROR: This Dockerfile must be built as root!" >&2; \
+      exit 1; \
+    fi
 ENV WODOO_SRC=/opt/wodoo
 ENV WODOO_PIPX_HOME=/opt/wodoo_pipx
 ENV WODOO_ENV_DIR=/opt/wodoo_pipx/venvs/wodoo
 ENV WODOO_PYTHON=$WODOO_ENV_DIR/bin/python3
+COPY --from=wodoo_src:latest /opt/wodoo "$WODOO_SRC"
 
 #___SNIPPET_PYTHON311___
 
-COPY --from=wodoo_src:latest /opt/wodoo "$WODOO_SRC"
-RUN chown -R $CURRENT_USER:$CURRENT_USER "$WODOO_SRC"
-
-
-
-RUN /usr/bin/python3.11 -m venv "$WODOO_ENV_DIR"; \
-     $WODOO_PYTHON -m pip install $PIP_OPTIONS --upgrade pip; \
-     $WODOO_PYTHON -m pip install $PIP_OPTIONS pipx setuptools wheel --upgrade;  
-
-RUN $WODOO_PYTHON -mpip install $PIP_OPTIONS lxml==4.9.3
+RUN /usr/bin/python3.11 -m venv "$WODOO_ENV_DIR" && \
+     $WODOO_PYTHON -m pip install $(cat /etc/pip_options) --upgrade pip && \
+     $WODOO_PYTHON -m pip install $(cat /etc/pip_options) pipx setuptools wheel --upgrade && \
+     $WODOO_PYTHON -mpip install $(cat /etc/pip_options) lxml==4.9.3
 
 RUN \
 if [ "$ODOO_VERSION"  != '11' ]; then \
@@ -34,8 +34,10 @@ if [ "$ODOO_VERSION"  != '11' ]; then \
           exit 1) \
 fi
 
-RUN echo 'export PATH=$PATH:$HOME/.local/bin' >> $HOME/.bashrc
-#RUN chmod a+rw -R "$WODOO_SRC" "$WODOO_PIPX_HOME" "$WODOO_ENV_DIR"
-RUN echo "export WODOO_PYTHON=$WODOO_PYTHON" >> /etc/bash.bashrc
-RUN echo "export WODOO_PYTHON=$WODOO_PYTHON" >> /etc/profile.d/wodoo_python.sh && \
-    chmod +x /etc/profile.d/wodoo_python.sh
+RUN \
+export HOME=/root && \
+mkdir -p $HOME/.local/bin && \
+echo 'export PATH=$PATH:$HOME/.local/bin' >> $HOME/.bashrc && \
+echo "export WODOO_PYTHON=$WODOO_PYTHON" >> /etc/bash.bashrc && \
+echo "export WODOO_PYTHON=$WODOO_PYTHON" >> /etc/profile.d/wodoo_python.sh && \
+chmod +x /etc/profile.d/wodoo_python.sh
