main: cleanup cleanup

diff --git a/postgres/Dockerfile.17 b/postgres/Dockerfile.17
--- a/postgres/Dockerfile.17
+++ b/postgres/Dockerfile.17
@@ -14,6 +14,11 @@ COPY init/* /docker-entrypoint-initdb.d/
 RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
     chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
 
+# CLEANUP
+
+RUN apt-get purge -y git git-core gnupg gnupg2 binutils
+RUN apt-get purge -y libgdal* libarmadillo* libogdi* libasan* libtsan* libubsan* || true
+
 #___SNIPPET_CLEANUP___
 RUN rm -Rf \
 /usr/share/perl \
@@ -26,8 +31,6 @@ RUN rm -Rf \
 /usr/lib/bfd-plugins \
 /usr/lib/git-core
 
-RUN apt-get purge -y git git-core gnupg gnupg2 binutils
-RUN apt-get purge -y libgdal* libarmadillo* libogdi* libasan* libtsan* libubsan* || true
 
 #/usr/lib/python*
 #/usr/lib/aarch* \
